## Global compose framework for minio
version: '3.4'

x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  minio:
    image: minio/minio:RELEASE.2019-09-11T19-53-16Z
    restart: unless-stopped
    command: "server /data"
    logging: *default-logging
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-12345}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-12345678}
    volumes:
      - ${MINIO_DATA_DIR:-./minio-data}:/data
    networks:
      - web
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio-insecure.entrypoints=http
      - traefik.http.routers.minio-insecure.rule=${MINIO_URL_CONFIG:-Host(`s3-minio-test.naturalis.nl`)}
      - traefik.http.routers.minio-insecure.middlewares=minio-redirectscheme@docker
      - traefik.http.middlewares.minio-redirectscheme.redirectscheme.scheme=https
      - traefik.http.middlewares.minio-redirectscheme.redirectscheme.permanent=true
      - traefik.http.routers.minio.entrypoints=https
      - traefik.http.routers.minio.tls.certresolver=transip
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.tls.domains[0].main=${MINIO_URL_DOMAIN:-s3-minio-test.naturalis.nl}
      - traefik.http.routers.minio.tls.domains[0].sans=*.${MINIO_URL_DOMAIN:-s3-minio-test.naturalis.nl}
      - traefik.http.routers.minio.rule=${MINIO_URL_CONFIG:-Host(`s3-minio-test.naturalis.nl`)}

  traefik:
    image: traefik:2.0.0
    restart: unless-stopped
    environment:
      - TRANSIP_PRIVATE_KEY_PATH=/.transip.key
      - TRANSIP_ACCOUNT_NAME=${TRANSIP_ACCOUNT_NAME:-naturalis}
    ports:
      - 80:80
      - 443:443
      - 8081:8080
    networks:
      - web
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${TRAEFIK_TOML_FILE:-./traefik.toml}:/traefik.toml
      - ./.transip.key:/.transip.key
      - ./acme.json:/acme.json
    logging: *default-logging

# run docker network create web before
networks:
  web:
    external: true


